name: Deploy to Github Pages
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Packages
        uses: bahmutov/npm-install@v1
      - name: Build Application
        run: node ./build.js
        env:
          WORKFLOW_PATH: /VTTExternalActorSites
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
